<?php

namespace Database\Seeders;

use App\Models\Airline;
use Illuminate\Database\Seeder;
use Illuminate\Support\Carbon;

class HubudAirlineSeeder extends Seeder
{
    public function run(): void
    {
        $now = Carbon::now();
        $sourceHubud = 'HUBUD_KEMENHUB';
        $sourceHubudProj = 'HUBUD_KEMENHUB+PROJECT_REFERENCE';
        $sourceProj = 'PROJECT_REFERENCE';
        $hubudUrl = 'https://hubud.kemenhub.go.id/hubud/website/maskapai';

        $airlines = [
            // ═════════════════════════════════════════════════════════════════
            // 1. AOC 121 — ANGKUTAN UDARA NIAGA BERJADWAL (DOMESTIK)
            // ═════════════════════════════════════════════════════════════════
            [
                'airline_code'      => 'GA',
                'airline_name'      => 'Garuda Indonesia',
                'organization_code' => 'AOC 121-001',
                'category'          => 'domestic',
                'country'           => 'Indonesia',
                'status'            => 'active',
                'is_active'         => true,
                'source'            => $sourceHubudProj,
                'source_url'        => $hubudUrl,
                'source_checked_at' => $now,
            ],
            [
                'airline_code'      => 'JT',
                'airline_name'      => 'Lion Air',
                'organization_code' => 'AOC 121-010',
                'category'          => 'domestic',
                'country'           => 'Indonesia',
                'status'            => 'active',
                'is_active'         => true,
                'source'            => $sourceHubudProj,
                'source_url'        => $hubudUrl,
                'source_checked_at' => $now,
            ],
            [
                'airline_code'      => 'QG',
                'airline_name'      => 'Citilink',
                'organization_code' => 'AOC 121-046',
                'category'          => 'domestic',
                'country'           => 'Indonesia',
                'status'            => 'active',
                'is_active'         => true,
                'source'            => $sourceHubudProj,
                'source_url'        => $hubudUrl,
                'source_checked_at' => $now,
            ],
            [
                'airline_code'      => 'IW',
                'airline_name'      => 'Wings Air',
                'organization_code' => 'AOC 121-014',
                'category'          => 'domestic',
                'country'           => 'Indonesia',
                'status'            => 'active',
                'is_active'         => true,
                'source'            => $sourceHubudProj,
                'source_url'        => $hubudUrl,
                'source_checked_at' => $now,
            ],
            [
                'airline_code'      => 'IU',
                'airline_name'      => 'Super Air Jet',
                'organization_code' => 'AOC 121-060',
                'category'          => 'domestic',
                'country'           => 'Indonesia',
                'status'            => 'active',
                'is_active'         => true,
                'source'            => $sourceHubudProj,
                'source_url'        => $hubudUrl,
                'source_checked_at' => $now,
            ],
            [
                'airline_code'      => '8B',
                'airline_name'      => 'TransNusa',
                'organization_code' => 'AOC 121-030',
                'category'          => 'domestic',
                'country'           => 'Indonesia',
                'status'            => 'active',
                'is_active'         => true,
                'source'            => $sourceHubudProj,
                'source_url'        => $hubudUrl,
                'source_checked_at' => $now,
            ],
            [
                'airline_code'      => 'ID',
                'airline_name'      => 'Batik Air',
                'organization_code' => 'AOC 121-053',
                'category'          => 'domestic',
                'country'           => 'Indonesia',
                'status'            => 'active',
                'is_active'         => true,
                'source'            => $sourceHubudProj,
                'source_url'        => $hubudUrl,
                'source_checked_at' => $now,
            ],
            [
                'airline_code'      => 'QZ',
                'airline_name'      => 'Indonesia AirAsia',
                'organization_code' => 'AOC 121-038',
                'category'          => 'domestic',
                'country'           => 'Indonesia',
                'status'            => 'active',
                'is_active'         => true,
                'source'            => $sourceHubudProj,
                'source_url'        => $hubudUrl,
                'source_checked_at' => $now,
            ],
            [
                'airline_code'      => 'SJ',
                'airline_name'      => 'Sriwijaya Air',
                'organization_code' => 'AOC 121-035',
                'category'          => 'domestic',
                'country'           => 'Indonesia',
                'status'            => 'active',
                'is_active'         => true,
                'source'            => $sourceHubudProj,
                'source_url'        => $hubudUrl,
                'source_checked_at' => $now,
            ],
            [
                'airline_code'      => 'IN',
                'airline_name'      => 'NAM Air',
                'organization_code' => 'AOC 121-058',
                'category'          => 'domestic',
                'country'           => 'Indonesia',
                'status'            => 'active',
                'is_active'         => true,
                'source'            => $sourceHubudProj,
                'source_url'        => $hubudUrl,
                'source_checked_at' => $now,
            ],
            [
                'airline_code'      => 'IP',
                'airline_name'      => 'Pelita Air',
                'organization_code' => 'AOC 121-008',
                'category'          => 'domestic',
                'country'           => 'Indonesia',
                'status'            => 'active',
                'is_active'         => true,
                'source'            => $sourceHubudProj,
                'source_url'        => $hubudUrl,
                'source_checked_at' => $now,
            ],
            [
                'airline_code'      => 'IL',
                'airline_name'      => 'Trigana Air',
                'organization_code' => 'AOC 121-006',
                'category'          => 'domestic',
                'country'           => 'Indonesia',
                'status'            => 'active',
                'is_active'         => true,
                'source'            => $sourceHubudProj,
                'source_url'        => $hubudUrl,
                'source_checked_at' => $now,
            ],
            [
                'airline_code'      => 'MV',
                'airline_name'      => 'Aviastar',
                'organization_code' => 'AOC 121-045',
                'category'          => 'domestic',
                'country'           => 'Indonesia',
                'status'            => 'active',
                'is_active'         => true,
                'source'            => $sourceHubudProj,
                'source_url'        => $hubudUrl,
                'source_checked_at' => $now,
            ],
            [
                'airline_code'      => 'XN',
                'airline_name'      => 'Express Air',
                'organization_code' => 'AOC 121-033',
                'category'          => 'domestic',
                'country'           => 'Indonesia',
                'status'            => 'inactive',
                'is_active'         => false,
                'source'            => $sourceHubudProj,
                'source_url'        => $hubudUrl,
                'source_checked_at' => $now,
            ],
            [
                'airline_code'      => 'KD',
                'airline_name'      => 'Kalstar Aviation',
                'organization_code' => 'AOC 121-041',
                'category'          => 'domestic',
                'country'           => 'Indonesia',
                'status'            => 'inactive',
                'is_active'         => false,
                'source'            => $sourceHubudProj,
                'source_url'        => $hubudUrl,
                'source_checked_at' => $now,
            ],
            [
                'airline_code'      => 'MZ',
                'airline_name'      => 'Merpati Nusantara',
                'organization_code' => 'AOC 121-002',
                'category'          => 'domestic',
                'country'           => 'Indonesia',
                'status'            => 'inactive',
                'is_active'         => false,
                'source'            => $sourceHubudProj,
                'source_url'        => $hubudUrl,
                'source_checked_at' => $now,
            ],
            [
                'airline_code'      => 'RI',
                'airline_name'      => 'Mandala Airlines',
                'organization_code' => 'AOC 121-005',
                'category'          => 'domestic',
                'country'           => 'Indonesia',
                'status'            => 'inactive',
                'is_active'         => false,
                'source'            => $sourceHubudProj,
                'source_url'        => $hubudUrl,
                'source_checked_at' => $now,
            ],
            [
                'airline_code'      => 'SY',
                'airline_name'      => 'Sky Aviation',
                'organization_code' => 'AOC 121-047',
                'category'          => 'domestic',
                'country'           => 'Indonesia',
                'status'            => 'inactive',
                'is_active'         => false,
                'source'            => $sourceHubudProj,
                'source_url'        => $hubudUrl,
                'source_checked_at' => $now,
            ],

            // ── AOC 121 CARGO OPERATORS ──────────────────────────────────────
            [
                'airline_code'      => '2Y',
                'airline_name'      => 'My Indo Airlines',
                'organization_code' => 'AOC 121-049',
                'category'          => 'cargo',
                'country'           => 'Indonesia',
                'status'            => 'active',
                'is_active'         => true,
                'source'            => $sourceHubud,
                'source_url'        => $hubudUrl,
                'source_checked_at' => $now,
            ],
            [
                'airline_code'      => '8C',
                'airline_name'      => 'Cardig Air',
                'organization_code' => 'AOC 121-026',
                'category'          => 'cargo',
                'country'           => 'Indonesia',
                'status'            => 'active',
                'is_active'         => true,
                'source'            => $sourceHubud,
                'source_url'        => $hubudUrl,
                'source_checked_at' => $now,
            ],
            [
                'airline_code'      => 'GY',
                'airline_name'      => 'Tri-M.G. Intra Asia Airlines',
                'organization_code' => 'AOC 121-019',
                'category'          => 'cargo',
                'country'           => 'Indonesia',
                'status'            => 'active',
                'is_active'         => true,
                'source'            => $sourceHubud,
                'source_url'        => $hubudUrl,
                'source_checked_at' => $now,
            ],

            // ═════════════════════════════════════════════════════════════════
            // 2. AOC 135 — ANGKUTAN UDARA TIDAK BERJADWAL / PERINTIS / CHARTER
            // ═════════════════════════════════════════════════════════════════
            [
                'airline_code'      => 'SI',
                'airline_name'      => 'Susi Air',
                'organization_code' => 'AOC 135-028',
                'category'          => 'domestic',
                'country'           => 'Indonesia',
                'status'            => 'active',
                'is_active'         => true,
                'source'            => $sourceHubudProj,
                'source_url'        => $hubudUrl,
                'source_checked_at' => $now,
            ],
            [
                'airline_code'      => 'SMA',
                'airline_name'      => 'Smart Aviation',
                'organization_code' => 'AOC 135-062',
                'category'          => 'domestic',
                'country'           => 'Indonesia',
                'status'            => 'active',
                'is_active'         => true,
                'source'            => $sourceHubud,
                'source_url'        => $hubudUrl,
                'source_checked_at' => $now,
            ],
            [
                'airline_code'      => 'TV',
                'airline_name'      => 'Travira Air',
                'organization_code' => 'AOC 135-015',
                'category'          => 'charter',
                'country'           => 'Indonesia',
                'status'            => 'active',
                'is_active'         => true,
                'source'            => $sourceHubud,
                'source_url'        => $hubudUrl,
                'source_checked_at' => $now,
            ],
            [
                'airline_code'      => 'SAM',
                'airline_name'      => 'SAM Air',
                'organization_code' => 'AOC 135-061',
                'category'          => 'domestic',
                'country'           => 'Indonesia',
                'status'            => 'active',
                'is_active'         => true,
                'source'            => $sourceHubud,
                'source_url'        => $hubudUrl,
                'source_checked_at' => $now,
            ],

            // ═════════════════════════════════════════════════════════════════
            // 3. ANGKUTAN UDARA ASING (INTERNATIONAL CARRIERS)
            // ═════════════════════════════════════════════════════════════════
            [
                'airline_code'      => 'TR',
                'airline_name'      => 'Scoot',
                'organization_code' => null,
                'category'          => 'international',
                'country'           => 'Singapore',
                'status'            => 'active',
                'is_active'         => true,
                'source'            => $sourceHubudProj,
                'source_url'        => 'https://www.flyscoot.com/',
                'source_checked_at' => $now,
            ],
            [
                'airline_code'      => 'SQ',
                'airline_name'      => 'Singapore Airlines',
                'organization_code' => null,
                'category'          => 'international',
                'country'           => 'Singapore',
                'status'            => 'active',
                'is_active'         => true,
                'source'            => $sourceHubudProj,
                'source_url'        => 'https://www.singaporeair.com/',
                'source_checked_at' => $now,
            ],
            [
                'airline_code'      => 'MI',
                'airline_name'      => 'SilkAir',
                'organization_code' => null,
                'category'          => 'international',
                'country'           => 'Singapore',
                'status'            => 'inactive',
                'is_active'         => false,
                'source'            => $sourceHubudProj,
                'source_url'        => 'https://www.singaporeair.com/',
                'source_checked_at' => $now,
            ],
            [
                'airline_code'      => '3K',
                'airline_name'      => 'Jetstar Asia',
                'organization_code' => null,
                'category'          => 'international',
                'country'           => 'Singapore',
                'status'            => 'active',
                'is_active'         => true,
                'source'            => $sourceHubudProj,
                'source_url'        => 'https://www.jetstar.com/',
                'source_checked_at' => $now,
            ],
            [
                'airline_code'      => 'MH',
                'airline_name'      => 'Malaysia Airlines',
                'organization_code' => null,
                'category'          => 'international',
                'country'           => 'Malaysia',
                'status'            => 'active',
                'is_active'         => true,
                'source'            => $sourceHubudProj,
                'source_url'        => 'https://www.malaysiaairlines.com/',
                'source_checked_at' => $now,
            ],
            [
                'airline_code'      => 'AK',
                'airline_name'      => 'AirAsia Berhad',
                'organization_code' => null,
                'category'          => 'international',
                'country'           => 'Malaysia',
                'status'            => 'active',
                'is_active'         => true,
                'source'            => $sourceHubudProj,
                'source_url'        => 'https://www.airasia.com/',
                'source_checked_at' => $now,
            ],
            [
                'airline_code'      => 'OD',
                'airline_name'      => 'Batik Air Malaysia',
                'organization_code' => null,
                'category'          => 'international',
                'country'           => 'Malaysia',
                'status'            => 'active',
                'is_active'         => true,
                'source'            => $sourceHubudProj,
                'source_url'        => 'https://www.batikair.com.my/',
                'source_checked_at' => $now,
            ],
            [
                'airline_code'      => 'TG',
                'airline_name'      => 'Thai Airways',
                'organization_code' => null,
                'category'          => 'international',
                'country'           => 'Thailand',
                'status'            => 'active',
                'is_active'         => true,
                'source'            => $sourceHubudProj,
                'source_url'        => 'https://www.thaiairways.com/',
                'source_checked_at' => $now,
            ],
            [
                'airline_code'      => 'FD',
                'airline_name'      => 'Thai AirAsia',
                'organization_code' => null,
                'category'          => 'international',
                'country'           => 'Thailand',
                'status'            => 'active',
                'is_active'         => true,
                'source'            => $sourceHubudProj,
                'source_url'        => 'https://www.airasia.com/',
                'source_checked_at' => $now,
            ],
            [
                'airline_code'      => 'SL',
                'airline_name'      => 'Thai Lion Air',
                'organization_code' => null,
                'category'          => 'international',
                'country'           => 'Thailand',
                'status'            => 'active',
                'is_active'         => true,
                'source'            => $sourceHubudProj,
                'source_url'        => 'https://www.lionairthai.com/',
                'source_checked_at' => $now,
            ],
            [
                'airline_code'      => 'VN',
                'airline_name'      => 'Vietnam Airlines',
                'organization_code' => null,
                'category'          => 'international',
                'country'           => 'Vietnam',
                'status'            => 'active',
                'is_active'         => true,
                'source'            => $sourceHubudProj,
                'source_url'        => 'https://www.vietnamairlines.com/',
                'source_checked_at' => $now,
            ],
            [
                'airline_code'      => 'VJ',
                'airline_name'      => 'VietJet Air',
                'organization_code' => null,
                'category'          => 'international',
                'country'           => 'Vietnam',
                'status'            => 'active',
                'is_active'         => true,
                'source'            => $sourceHubudProj,
                'source_url'        => 'https://www.vietjetair.com/',
                'source_checked_at' => $now,
            ],
            [
                'airline_code'      => 'PR',
                'airline_name'      => 'Philippine Airlines',
                'organization_code' => null,
                'category'          => 'international',
                'country'           => 'Philippines',
                'status'            => 'active',
                'is_active'         => true,
                'source'            => $sourceHubudProj,
                'source_url'        => 'https://www.philippineairlines.com/',
                'source_checked_at' => $now,
            ],
            [
                'airline_code'      => '5J',
                'airline_name'      => 'Cebu Pacific',
                'organization_code' => null,
                'category'          => 'international',
                'country'           => 'Philippines',
                'status'            => 'active',
                'is_active'         => true,
                'source'            => $sourceHubudProj,
                'source_url'        => 'https://www.cebupacificair.com/',
                'source_checked_at' => $now,
            ],
            [
                'airline_code'      => 'CX',
                'airline_name'      => 'Cathay Pacific',
                'organization_code' => null,
                'category'          => 'international',
                'country'           => 'Hong Kong',
                'status'            => 'active',
                'is_active'         => true,
                'source'            => $sourceHubudProj,
                'source_url'        => 'https://www.cathaypacific.com/',
                'source_checked_at' => $now,
            ],
            [
                'airline_code'      => 'CI',
                'airline_name'      => 'China Airlines',
                'organization_code' => null,
                'category'          => 'international',
                'country'           => 'Taiwan',
                'status'            => 'active',
                'is_active'         => true,
                'source'            => $sourceHubudProj,
                'source_url'        => 'https://www.china-airlines.com/',
                'source_checked_at' => $now,
            ],
            [
                'airline_code'      => 'BR',
                'airline_name'      => 'EVA Air',
                'organization_code' => null,
                'category'          => 'international',
                'country'           => 'Taiwan',
                'status'            => 'active',
                'is_active'         => true,
                'source'            => $sourceHubudProj,
                'source_url'        => 'https://www.evaair.com/',
                'source_checked_at' => $now,
            ],
            [
                'airline_code'      => 'CA',
                'airline_name'      => 'Air China',
                'organization_code' => null,
                'category'          => 'international',
                'country'           => 'China',
                'status'            => 'active',
                'is_active'         => true,
                'source'            => $sourceHubudProj,
                'source_url'        => 'https://www.airchina.com/',
                'source_checked_at' => $now,
            ],
            [
                'airline_code'      => 'CZ',
                'airline_name'      => 'China Southern Airlines',
                'organization_code' => null,
                'category'          => 'international',
                'country'           => 'China',
                'status'            => 'active',
                'is_active'         => true,
                'source'            => $sourceHubudProj,
                'source_url'        => 'https://www.csair.com/',
                'source_checked_at' => $now,
            ],
            [
                'airline_code'      => 'MU',
                'airline_name'      => 'China Eastern Airlines',
                'organization_code' => null,
                'category'          => 'international',
                'country'           => 'China',
                'status'            => 'active',
                'is_active'         => true,
                'source'            => $sourceHubudProj,
                'source_url'        => 'https://www.ceair.com/',
                'source_checked_at' => $now,
            ],
            [
                'airline_code'      => 'MF',
                'airline_name'      => 'XiamenAir',
                'organization_code' => null,
                'category'          => 'international',
                'country'           => 'China',
                'status'            => 'active',
                'is_active'         => true,
                'source'            => $sourceHubudProj,
                'source_url'        => 'https://www.xiamenair.com/',
                'source_checked_at' => $now,
            ],
            [
                'airline_code'      => 'JL',
                'airline_name'      => 'Japan Airlines',
                'organization_code' => null,
                'category'          => 'international',
                'country'           => 'Japan',
                'status'            => 'active',
                'is_active'         => true,
                'source'            => $sourceHubudProj,
                'source_url'        => 'https://www.jal.co.jp/',
                'source_checked_at' => $now,
            ],
            [
                'airline_code'      => 'NH',
                'airline_name'      => 'All Nippon Airways (ANA)',
                'organization_code' => null,
                'category'          => 'international',
                'country'           => 'Japan',
                'status'            => 'active',
                'is_active'         => true,
                'source'            => $sourceHubudProj,
                'source_url'        => 'https://www.ana.co.jp/',
                'source_checked_at' => $now,
            ],
            [
                'airline_code'      => 'KE',
                'airline_name'      => 'Korean Air',
                'organization_code' => null,
                'category'          => 'international',
                'country'           => 'South Korea',
                'status'            => 'active',
                'is_active'         => true,
                'source'            => $sourceHubudProj,
                'source_url'        => 'https://www.koreanair.com/',
                'source_checked_at' => $now,
            ],
            [
                'airline_code'      => 'OZ',
                'airline_name'      => 'Asiana Airlines',
                'organization_code' => null,
                'category'          => 'international',
                'country'           => 'South Korea',
                'status'            => 'active',
                'is_active'         => true,
                'source'            => $sourceHubudProj,
                'source_url'        => 'https://flyasiana.com/',
                'source_checked_at' => $now,
            ],
            [
                'airline_code'      => 'EK',
                'airline_name'      => 'Emirates',
                'organization_code' => null,
                'category'          => 'international',
                'country'           => 'United Arab Emirates',
                'status'            => 'active',
                'is_active'         => true,
                'source'            => $sourceHubudProj,
                'source_url'        => 'https://www.emirates.com/',
                'source_checked_at' => $now,
            ],
            [
                'airline_code'      => 'QR',
                'airline_name'      => 'Qatar Airways',
                'organization_code' => null,
                'category'          => 'international',
                'country'           => 'Qatar',
                'status'            => 'active',
                'is_active'         => true,
                'source'            => $sourceHubudProj,
                'source_url'        => 'https://www.qatarairways.com/',
                'source_checked_at' => $now,
            ],
            [
                'airline_code'      => 'EY',
                'airline_name'      => 'Etihad Airways',
                'organization_code' => null,
                'category'          => 'international',
                'country'           => 'United Arab Emirates',
                'status'            => 'active',
                'is_active'         => true,
                'source'            => $sourceHubudProj,
                'source_url'        => 'https://www.etihad.com/',
                'source_checked_at' => $now,
            ],
            [
                'airline_code'      => 'SV',
                'airline_name'      => 'Saudia',
                'organization_code' => null,
                'category'          => 'international',
                'country'           => 'Saudi Arabia',
                'status'            => 'active',
                'is_active'         => true,
                'source'            => $sourceHubudProj,
                'source_url'        => 'https://www.saudia.com/',
                'source_checked_at' => $now,
            ],
            [
                'airline_code'      => 'TK',
                'airline_name'      => 'Turkish Airlines',
                'organization_code' => null,
                'category'          => 'international',
                'country'           => 'Turkey',
                'status'            => 'active',
                'is_active'         => true,
                'source'            => $sourceHubudProj,
                'source_url'        => 'https://www.turkishairlines.com/',
                'source_checked_at' => $now,
            ],
            [
                'airline_code'      => 'QF',
                'airline_name'      => 'Qantas Airways',
                'organization_code' => null,
                'category'          => 'international',
                'country'           => 'Australia',
                'status'            => 'active',
                'is_active'         => true,
                'source'            => $sourceHubudProj,
                'source_url'        => 'https://www.qantas.com/',
                'source_checked_at' => $now,
            ],
            [
                'airline_code'      => 'JQ',
                'airline_name'      => 'Jetstar Airways',
                'organization_code' => null,
                'category'          => 'international',
                'country'           => 'Australia',
                'status'            => 'active',
                'is_active'         => true,
                'source'            => $sourceHubudProj,
                'source_url'        => 'https://www.jetstar.com/',
                'source_checked_at' => $now,
            ],
            [
                'airline_code'      => 'VA',
                'airline_name'      => 'Virgin Australia',
                'organization_code' => null,
                'category'          => 'international',
                'country'           => 'Australia',
                'status'            => 'active',
                'is_active'         => true,
                'source'            => $sourceHubudProj,
                'source_url'        => 'https://www.virginaustralia.com/',
                'source_checked_at' => $now,
            ],
            [
                'airline_code'      => 'KL',
                'airline_name'      => 'KLM Royal Dutch Airlines',
                'organization_code' => null,
                'category'          => 'international',
                'country'           => 'Netherlands',
                'status'            => 'active',
                'is_active'         => true,
                'source'            => $sourceHubudProj,
                'source_url'        => 'https://www.klm.com/',
                'source_checked_at' => $now,
            ],
            [
                'airline_code'      => 'AF',
                'airline_name'      => 'Air France',
                'organization_code' => null,
                'category'          => 'international',
                'country'           => 'France',
                'status'            => 'active',
                'is_active'         => true,
                'source'            => $sourceHubudProj,
                'source_url'        => 'https://www.airfrance.com/',
                'source_checked_at' => $now,
            ],
            [
                'airline_code'      => 'LH',
                'airline_name'      => 'Lufthansa',
                'organization_code' => null,
                'category'          => 'international',
                'country'           => 'Germany',
                'status'            => 'active',
                'is_active'         => true,
                'source'            => $sourceHubudProj,
                'source_url'        => 'https://www.lufthansa.com/',
                'source_checked_at' => $now,
            ],
            [
                'airline_code'      => 'ET',
                'airline_name'      => 'Ethiopian Airlines',
                'organization_code' => null,
                'category'          => 'international',
                'country'           => 'Ethiopia',
                'status'            => 'active',
                'is_active'         => true,
                'source'            => $sourceHubudProj,
                'source_url'        => 'https://www.ethiopianairlines.com/',
                'source_checked_at' => $now,
            ],
        ];

        foreach ($airlines as $al) {
            Airline::updateOrCreate(
                ['airline_code' => $al['airline_code']],
                $al
            );
        }
    }
}
