<?php

namespace Database\Seeders;

use App\Models\Airport;
use Illuminate\Database\Seeder;
use Illuminate\Support\Carbon;

class HubudAirportSeeder extends Seeder
{
    public function run(): void
    {
        $now = Carbon::now();

        $srcInjourney = Airport::SOURCE_INJOURNEY;
        $srcRef       = Airport::SOURCE_REFERENCE;

        $injourneyUrl = 'https://injourneyairports.id/airport/map-selection';

        $mgmtInjourney = Airport::MANAGEMENT_INJOURNEY;
        $mgmtOther     = Airport::MANAGEMENT_OTHER;

        $airports = [
            // ═════════════════════════════════════════════════════════════════
            // PRIORITY 1: PT. ANGKASA PURA INDONESIA / INJOURNEY AIRPORTS
            // EXACTLY 37 BANDARA (28 INTL, 9 DOM) — STRICTLY LOCKED MASTER
            // ═════════════════════════════════════════════════════════════════

            // ── REGION 1 (4 Bandara: 3 INTL, 1 DOM) ───────────────────────────
            [
                'iata_code'        => 'CGK',
                'icao_code'        => 'WIII',
                'name'             => 'Soekarno-Hatta',
                'city'             => 'Tangerang / Jakarta',
                'province'         => 'Banten',
                'region'           => 'Region 1',
                'country'          => 'Indonesia',
                'airport_type'     => 'international',
                'management_type'  => $mgmtInjourney,
                'management_name'  => 'PT. Angkasa Pura Indonesia',
                'usage_type'       => 'Komersial',
                'classification'   => 'Kelas I Utama',
                'status'           => 'active',
                'is_international' => true,
                'is_active'        => true,
                'data_incomplete'  => false,
                'data_source'      => $srcInjourney,
                'source'           => $srcInjourney,
                'source_url'       => $injourneyUrl,
                'source_checked_at'=> $now,
            ],
            [
                'iata_code'        => 'HLP',
                'icao_code'        => 'WIHH',
                'name'             => 'Halim Perdanakusuma',
                'city'             => 'Jakarta Timur',
                'province'         => 'DKI Jakarta',
                'region'           => 'Region 1',
                'country'          => 'Indonesia',
                'airport_type'     => 'international',
                'management_type'  => $mgmtInjourney,
                'management_name'  => 'PT. Angkasa Pura Indonesia',
                'usage_type'       => 'Komersial / Militer',
                'classification'   => 'Kelas I Utama',
                'status'           => 'active',
                'is_international' => true,
                'is_active'        => true,
                'data_incomplete'  => false,
                'data_source'      => $srcInjourney,
                'source'           => $srcInjourney,
                'source_url'       => $injourneyUrl,
                'source_checked_at'=> $now,
            ],
            [
                'iata_code'        => 'KJT',
                'icao_code'        => 'WICA',
                'name'             => 'Kertajati',
                'city'             => 'Majalengka',
                'province'         => 'Jawa Barat',
                'region'           => 'Region 1',
                'country'          => 'Indonesia',
                'airport_type'     => 'international',
                'management_type'  => $mgmtInjourney,
                'management_name'  => 'PT. Angkasa Pura Indonesia',
                'usage_type'       => 'Komersial',
                'classification'   => 'Kelas I Utama',
                'status'           => 'active',
                'is_international' => true,
                'is_active'        => true,
                'data_incomplete'  => false,
                'data_source'      => $srcInjourney,
                'source'           => $srcInjourney,
                'source_url'       => $injourneyUrl,
                'source_checked_at'=> $now,
            ],
            [
                'iata_code'        => 'BDO',
                'icao_code'        => 'WICC',
                'name'             => 'Husein Sastranegara',
                'city'             => 'Bandung',
                'province'         => 'Jawa Barat',
                'region'           => 'Region 1',
                'country'          => 'Indonesia',
                'airport_type'     => 'domestic',
                'management_type'  => $mgmtInjourney,
                'management_name'  => 'PT. Angkasa Pura Indonesia',
                'usage_type'       => 'Komersial / Pangkalan Militer',
                'classification'   => 'Kelas I',
                'status'           => 'active',
                'is_international' => false,
                'is_active'        => true,
                'data_incomplete'  => false,
                'data_source'      => $srcInjourney,
                'source'           => $srcInjourney,
                'source_url'       => $injourneyUrl,
                'source_checked_at'=> $now,
            ],

            // ── REGION 2 (4 Bandara: 2 INTL, 2 DOM) ───────────────────────────
            [
                'iata_code'        => 'DPS',
                'icao_code'        => 'WADD',
                'name'             => 'I Gusti Ngurah Rai',
                'city'             => 'Denpasar / Badung',
                'province'         => 'Bali',
                'region'           => 'Region 2',
                'country'          => 'Indonesia',
                'airport_type'     => 'international',
                'management_type'  => $mgmtInjourney,
                'management_name'  => 'PT. Angkasa Pura Indonesia',
                'usage_type'       => 'Komersial',
                'classification'   => 'Kelas I Utama',
                'status'           => 'active',
                'is_international' => true,
                'is_active'        => true,
                'data_incomplete'  => false,
                'data_source'      => $srcInjourney,
                'source'           => $srcInjourney,
                'source_url'       => $injourneyUrl,
                'source_checked_at'=> $now,
            ],
            [
                'iata_code'        => 'BWX',
                'icao_code'        => 'WADY',
                'name'             => 'Banyuwangi',
                'city'             => 'Banyuwangi',
                'province'         => 'Jawa Timur',
                'region'           => 'Region 2',
                'country'          => 'Indonesia',
                'airport_type'     => 'international',
                'management_type'  => $mgmtInjourney,
                'management_name'  => 'PT. Angkasa Pura Indonesia',
                'usage_type'       => 'Komersial',
                'classification'   => 'Kelas II',
                'status'           => 'active',
                'is_international' => true,
                'is_active'        => true,
                'data_incomplete'  => false,
                'data_source'      => $srcInjourney,
                'source'           => $srcInjourney,
                'source_url'       => $injourneyUrl,
                'source_checked_at'=> $now,
            ],
            [
                'iata_code'        => 'LOP',
                'icao_code'        => 'WADL',
                'name'             => 'Zainuddin Abdul Madjid (Lombok)',
                'city'             => 'Praya / Lombok Tengah',
                'province'         => 'Nusa Tenggara Barat',
                'region'           => 'Region 2',
                'country'          => 'Indonesia',
                'airport_type'     => 'domestic',
                'management_type'  => $mgmtInjourney,
                'management_name'  => 'PT. Angkasa Pura Indonesia',
                'usage_type'       => 'Komersial',
                'classification'   => 'Kelas I',
                'status'           => 'active',
                'is_international' => false,
                'is_active'        => true,
                'data_incomplete'  => false,
                'data_source'      => $srcInjourney,
                'source'           => $srcInjourney,
                'source_url'       => $injourneyUrl,
                'source_checked_at'=> $now,
            ],
            [
                'iata_code'        => 'KOE',
                'icao_code'        => 'WATT',
                'name'             => 'El Tari',
                'city'             => 'Kupang',
                'province'         => 'Nusa Tenggara Timur',
                'region'           => 'Region 2',
                'country'          => 'Indonesia',
                'airport_type'     => 'domestic',
                'management_type'  => $mgmtInjourney,
                'management_name'  => 'PT. Angkasa Pura Indonesia',
                'usage_type'       => 'Komersial / Militer',
                'classification'   => 'Kelas I',
                'status'           => 'active',
                'is_international' => false,
                'is_active'        => true,
                'data_incomplete'  => false,
                'data_source'      => $srcInjourney,
                'source'           => $srcInjourney,
                'source_url'       => $injourneyUrl,
                'source_checked_at'=> $now,
            ],

            // ── REGION 3 (13 Bandara: 10 INTL, 3 DOM) ─────────────────────────
            [
                'iata_code'        => 'BTH',
                'icao_code'        => 'WIDD',
                'name'             => 'Hang Nadim',
                'city'             => 'Batam',
                'province'         => 'Kepulauan Riau',
                'region'           => 'Region 3',
                'country'          => 'Indonesia',
                'airport_type'     => 'international',
                'management_type'  => $mgmtInjourney,
                'management_name'  => 'PT. Angkasa Pura Indonesia',
                'usage_type'       => 'Komersial',
                'classification'   => 'Kelas I Utama',
                'status'           => 'active',
                'is_international' => true,
                'is_active'        => true,
                'data_incomplete'  => false,
                'data_source'      => $srcInjourney,
                'source'           => $srcInjourney,
                'source_url'       => $injourneyUrl,
                'source_checked_at'=> $now,
            ],
            [
                'iata_code'        => 'TNJ',
                'icao_code'        => 'WIDN',
                'name'             => 'Raja Haji Fisabilillah',
                'city'             => 'Tanjung Pinang',
                'province'         => 'Kepulauan Riau',
                'region'           => 'Region 3',
                'country'          => 'Indonesia',
                'airport_type'     => 'international',
                'management_type'  => $mgmtInjourney,
                'management_name'  => 'PT. Angkasa Pura Indonesia',
                'usage_type'       => 'Komersial',
                'classification'   => 'Kelas II',
                'status'           => 'active',
                'is_international' => true,
                'is_active'        => true,
                'data_incomplete'  => false,
                'data_source'      => $srcInjourney,
                'source'           => $srcInjourney,
                'source_url'       => $injourneyUrl,
                'source_checked_at'=> $now,
            ],
            [
                'iata_code'        => 'TJQ',
                'icao_code'        => 'WIKD',
                'name'             => 'H.A.S. Hanandjoeddin',
                'city'             => 'Tanjung Pandan / Belitung',
                'province'         => 'Kepulauan Bangka Belitung',
                'region'           => 'Region 3',
                'country'          => 'Indonesia',
                'airport_type'     => 'international',
                'management_type'  => $mgmtInjourney,
                'management_name'  => 'PT. Angkasa Pura Indonesia',
                'usage_type'       => 'Komersial',
                'classification'   => 'Kelas I',
                'status'           => 'active',
                'is_international' => true,
                'is_active'        => true,
                'data_incomplete'  => false,
                'data_source'      => $srcInjourney,
                'source'           => $srcInjourney,
                'source_url'       => $injourneyUrl,
                'source_checked_at'=> $now,
            ],
            [
                'iata_code'        => 'KNO',
                'icao_code'        => 'WIMM',
                'name'             => 'Kualanamu',
                'city'             => 'Deli Serdang / Medan',
                'province'         => 'Sumatera Utara',
                'region'           => 'Region 3',
                'country'          => 'Indonesia',
                'airport_type'     => 'international',
                'management_type'  => $mgmtInjourney,
                'management_name'  => 'PT. Angkasa Pura Indonesia',
                'usage_type'       => 'Komersial',
                'classification'   => 'Kelas I Utama',
                'status'           => 'active',
                'is_international' => true,
                'is_active'        => true,
                'data_incomplete'  => false,
                'data_source'      => $srcInjourney,
                'source'           => $srcInjourney,
                'source_url'       => $injourneyUrl,
                'source_checked_at'=> $now,
            ],
            [
                'iata_code'        => 'DTB',
                'icao_code'        => 'WIMP',
                'name'             => 'Raja Sisingamangaraja XII (Silangit)',
                'city'             => 'Siborong-borong / Tapanuli Utara',
                'province'         => 'Sumatera Utara',
                'region'           => 'Region 3',
                'country'          => 'Indonesia',
                'airport_type'     => 'international',
                'management_type'  => $mgmtInjourney,
                'management_name'  => 'PT. Angkasa Pura Indonesia',
                'usage_type'       => 'Komersial',
                'classification'   => 'Kelas II',
                'status'           => 'active',
                'is_international' => true,
                'is_active'        => true,
                'data_incomplete'  => false,
                'data_source'      => $srcInjourney,
                'source'           => $srcInjourney,
                'source_url'       => $injourneyUrl,
                'source_checked_at'=> $now,
            ],
            [
                'iata_code'        => 'PDG',
                'icao_code'        => 'WIEE',
                'name'             => 'Minangkabau',
                'city'             => 'Padang Pariaman / Padang',
                'province'         => 'Sumatera Barat',
                'region'           => 'Region 3',
                'country'          => 'Indonesia',
                'airport_type'     => 'international',
                'management_type'  => $mgmtInjourney,
                'management_name'  => 'PT. Angkasa Pura Indonesia',
                'usage_type'       => 'Komersial',
                'classification'   => 'Kelas I Utama',
                'status'           => 'active',
                'is_international' => true,
                'is_active'        => true,
                'data_incomplete'  => false,
                'data_source'      => $srcInjourney,
                'source'           => $srcInjourney,
                'source_url'       => $injourneyUrl,
                'source_checked_at'=> $now,
            ],
            [
                'iata_code'        => 'BTJ',
                'icao_code'        => 'WITT',
                'name'             => 'Sultan Iskandar Muda',
                'city'             => 'Banda Aceh / Aceh Besar',
                'province'         => 'Aceh',
                'region'           => 'Region 3',
                'country'          => 'Indonesia',
                'airport_type'     => 'international',
                'management_type'  => $mgmtInjourney,
                'management_name'  => 'PT. Angkasa Pura Indonesia',
                'usage_type'       => 'Komersial / Militer',
                'classification'   => 'Kelas I',
                'status'           => 'active',
                'is_international' => true,
                'is_active'        => true,
                'data_incomplete'  => false,
                'data_source'      => $srcInjourney,
                'source'           => $srcInjourney,
                'source_url'       => $injourneyUrl,
                'source_checked_at'=> $now,
            ],
            [
                'iata_code'        => 'PLM',
                'icao_code'        => 'WIPP',
                'name'             => 'Sultan Mahmud Badaruddin II',
                'city'             => 'Palembang',
                'province'         => 'Sumatera Selatan',
                'region'           => 'Region 3',
                'country'          => 'Indonesia',
                'airport_type'     => 'international',
                'management_type'  => $mgmtInjourney,
                'management_name'  => 'PT. Angkasa Pura Indonesia',
                'usage_type'       => 'Komersial / Militer',
                'classification'   => 'Kelas I Utama',
                'status'           => 'active',
                'is_international' => true,
                'is_active'        => true,
                'data_incomplete'  => false,
                'data_source'      => $srcInjourney,
                'source'           => $srcInjourney,
                'source_url'       => $injourneyUrl,
                'source_checked_at'=> $now,
            ],
            [
                'iata_code'        => 'PKU',
                'icao_code'        => 'WIBB',
                'name'             => 'Sultan Syarif Kasim II',
                'city'             => 'Pekanbaru',
                'province'         => 'Riau',
                'region'           => 'Region 3',
                'country'          => 'Indonesia',
                'airport_type'     => 'international',
                'management_type'  => $mgmtInjourney,
                'management_name'  => 'PT. Angkasa Pura Indonesia',
                'usage_type'       => 'Komersial / Lanud Roesmin Nurjadin',
                'classification'   => 'Kelas I Utama',
                'status'           => 'active',
                'is_international' => true,
                'is_active'        => true,
                'data_incomplete'  => false,
                'data_source'      => $srcInjourney,
                'source'           => $srcInjourney,
                'source_url'       => $injourneyUrl,
                'source_checked_at'=> $now,
            ],
            [
                'iata_code'        => 'TKG',
                'icao_code'        => 'WILL',
                'name'             => 'Radin Inten II',
                'city'             => 'Bandar Lampung / Lampung Selatan',
                'province'         => 'Lampung',
                'region'           => 'Region 3',
                'country'          => 'Indonesia',
                'airport_type'     => 'international',
                'management_type'  => $mgmtInjourney,
                'management_name'  => 'PT. Angkasa Pura Indonesia',
                'usage_type'       => 'Komersial',
                'classification'   => 'Kelas I',
                'status'           => 'active',
                'is_international' => true,
                'is_active'        => true,
                'data_incomplete'  => false,
                'data_source'      => $srcInjourney,
                'source'           => $srcInjourney,
                'source_url'       => $injourneyUrl,
                'source_checked_at'=> $now,
            ],
            [
                'iata_code'        => 'PGK',
                'icao_code'        => 'WIPK',
                'name'             => 'Depati Amir',
                'city'             => 'Pangkal Pinang',
                'province'         => 'Kepulauan Bangka Belitung',
                'region'           => 'Region 3',
                'country'          => 'Indonesia',
                'airport_type'     => 'domestic',
                'management_type'  => $mgmtInjourney,
                'management_name'  => 'PT. Angkasa Pura Indonesia',
                'usage_type'       => 'Komersial',
                'classification'   => 'Kelas I',
                'status'           => 'active',
                'is_international' => false,
                'is_active'        => true,
                'data_incomplete'  => false,
                'data_source'      => $srcInjourney,
                'source'           => $srcInjourney,
                'source_url'       => $injourneyUrl,
                'source_checked_at'=> $now,
            ],
            [
                'iata_code'        => 'BKS',
                'icao_code'        => 'WIGG',
                'name'             => 'Fatmawati Soekarno',
                'city'             => 'Bengkulu',
                'province'         => 'Bengkulu',
                'region'           => 'Region 3',
                'country'          => 'Indonesia',
                'airport_type'     => 'domestic',
                'management_type'  => $mgmtInjourney,
                'management_name'  => 'PT. Angkasa Pura Indonesia',
                'usage_type'       => 'Komersial',
                'classification'   => 'Kelas I',
                'status'           => 'active',
                'is_international' => false,
                'is_active'        => true,
                'data_incomplete'  => false,
                'data_source'      => $srcInjourney,
                'source'           => $srcInjourney,
                'source_url'       => $injourneyUrl,
                'source_checked_at'=> $now,
            ],
            [
                'iata_code'        => 'DJB',
                'icao_code'        => 'WIJJ',
                'name'             => 'Sultan Thaha',
                'city'             => 'Jambi',
                'province'         => 'Jambi',
                'region'           => 'Region 3',
                'country'          => 'Indonesia',
                'airport_type'     => 'domestic',
                'management_type'  => $mgmtInjourney,
                'management_name'  => 'PT. Angkasa Pura Indonesia',
                'usage_type'       => 'Komersial',
                'classification'   => 'Kelas I',
                'status'           => 'active',
                'is_international' => false,
                'is_active'        => true,
                'data_incomplete'  => false,
                'data_source'      => $srcInjourney,
                'source'           => $srcInjourney,
                'source_url'       => $injourneyUrl,
                'source_checked_at'=> $now,
            ],

            // ── REGION 4 (7 Bandara: 4 INTL, 3 DOM) ───────────────────────────
            [
                'iata_code'        => 'YIA',
                'icao_code'        => 'WAHI',
                'name'             => 'Yogyakarta International Airport',
                'city'             => 'Kulon Progo / Yogyakarta',
                'province'         => 'D.I. Yogyakarta',
                'region'           => 'Region 4',
                'country'          => 'Indonesia',
                'airport_type'     => 'international',
                'management_type'  => $mgmtInjourney,
                'management_name'  => 'PT. Angkasa Pura Indonesia',
                'usage_type'       => 'Komersial',
                'classification'   => 'Kelas I Utama',
                'status'           => 'active',
                'is_international' => true,
                'is_active'        => true,
                'data_incomplete'  => false,
                'data_source'      => $srcInjourney,
                'source'           => $srcInjourney,
                'source_url'       => $injourneyUrl,
                'source_checked_at'=> $now,
            ],
            [
                'iata_code'        => 'SRG',
                'icao_code'        => 'WAHS',
                'name'             => 'Jenderal Ahmad Yani',
                'city'             => 'Semarang',
                'province'         => 'Jawa Tengah',
                'region'           => 'Region 4',
                'country'          => 'Indonesia',
                'airport_type'     => 'international',
                'management_type'  => $mgmtInjourney,
                'management_name'  => 'PT. Angkasa Pura Indonesia',
                'usage_type'       => 'Komersial / Militer (Penerbad)',
                'classification'   => 'Kelas I Utama',
                'status'           => 'active',
                'is_international' => true,
                'is_active'        => true,
                'data_incomplete'  => false,
                'data_source'      => $srcInjourney,
                'source'           => $srcInjourney,
                'source_url'       => $injourneyUrl,
                'source_checked_at'=> $now,
            ],
            [
                'iata_code'        => 'SOC',
                'icao_code'        => 'WAHQ',
                'name'             => 'Adi Soemarmo',
                'city'             => 'Boyolali / Surakarta (Solo)',
                'province'         => 'Jawa Tengah',
                'region'           => 'Region 4',
                'country'          => 'Indonesia',
                'airport_type'     => 'international',
                'management_type'  => $mgmtInjourney,
                'management_name'  => 'PT. Angkasa Pura Indonesia',
                'usage_type'       => 'Komersial / Lanud TNI AU',
                'classification'   => 'Kelas I',
                'status'           => 'active',
                'is_international' => true,
                'is_active'        => true,
                'data_incomplete'  => false,
                'data_source'      => $srcInjourney,
                'source'           => $srcInjourney,
                'source_url'       => $injourneyUrl,
                'source_checked_at'=> $now,
            ],
            [
                'iata_code'        => 'SUB',
                'icao_code'        => 'WARR',
                'name'             => 'Juanda',
                'city'             => 'Sidoarjo / Surabaya',
                'province'         => 'Jawa Timur',
                'region'           => 'Region 4',
                'country'          => 'Indonesia',
                'airport_type'     => 'international',
                'management_type'  => $mgmtInjourney,
                'management_name'  => 'PT. Angkasa Pura Indonesia',
                'usage_type'       => 'Komersial / Pangkalan Militer AL',
                'classification'   => 'Kelas I Utama',
                'status'           => 'active',
                'is_international' => true,
                'is_active'        => true,
                'data_incomplete'  => false,
                'data_source'      => $srcInjourney,
                'source'           => $srcInjourney,
                'source_url'       => $injourneyUrl,
                'source_checked_at'=> $now,
            ],
            [
                'iata_code'        => 'DHX',
                'icao_code'        => 'WARD',
                'name'             => 'Dhoho',
                'city'             => 'Kediri',
                'province'         => 'Jawa Timur',
                'region'           => 'Region 4',
                'country'          => 'Indonesia',
                'airport_type'     => 'domestic',
                'management_type'  => $mgmtInjourney,
                'management_name'  => 'PT. Angkasa Pura Indonesia',
                'usage_type'       => 'Komersial',
                'classification'   => 'Kelas I',
                'status'           => 'active',
                'is_international' => false,
                'is_active'        => true,
                'data_incomplete'  => false,
                'data_source'      => $srcInjourney,
                'source'           => $srcInjourney,
                'source_url'       => $injourneyUrl,
                'source_checked_at'=> $now,
            ],
            [
                'iata_code'        => 'JOG',
                'icao_code'        => 'WAHH',
                'name'             => 'Adisutjipto',
                'city'             => 'Sleman / Yogyakarta',
                'province'         => 'D.I. Yogyakarta',
                'region'           => 'Region 4',
                'country'          => 'Indonesia',
                'airport_type'     => 'domestic',
                'management_type'  => $mgmtInjourney,
                'management_name'  => 'PT. Angkasa Pura Indonesia',
                'usage_type'       => 'Komersial / Lanud TNI AU',
                'classification'   => 'Kelas I',
                'status'           => 'active',
                'is_international' => false,
                'is_active'        => true,
                'data_incomplete'  => false,
                'data_source'      => $srcInjourney,
                'source'           => $srcInjourney,
                'source_url'       => $injourneyUrl,
                'source_checked_at'=> $now,
            ],
            [
                'iata_code'        => 'PWL',
                'icao_code'        => 'WAHP',
                'name'             => 'Jenderal Besar Soedirman (Wirasaba)',
                'city'             => 'Purbalingga',
                'province'         => 'Jawa Tengah',
                'region'           => 'Region 4',
                'country'          => 'Indonesia',
                'airport_type'     => 'domestic',
                'management_type'  => $mgmtInjourney,
                'management_name'  => 'PT. Angkasa Pura Indonesia',
                'usage_type'       => 'Komersial / Lanud TNI AU',
                'classification'   => 'Kelas III',
                'status'           => 'active',
                'is_international' => false,
                'is_active'        => true,
                'data_incomplete'  => false,
                'data_source'      => $srcInjourney,
                'source'           => $srcInjourney,
                'source_url'       => $injourneyUrl,
                'source_checked_at'=> $now,
            ],

            // ── REGION 5 (5 Bandara: 5 INTL, 0 DOM) ───────────────────────────
            [
                'iata_code'        => 'UPG',
                'icao_code'        => 'WAAA',
                'name'             => 'Sultan Hasanuddin',
                'city'             => 'Maros / Makassar',
                'province'         => 'Sulawesi Selatan',
                'region'           => 'Region 5',
                'country'          => 'Indonesia',
                'airport_type'     => 'international',
                'management_type'  => $mgmtInjourney,
                'management_name'  => 'PT. Angkasa Pura Indonesia',
                'usage_type'       => 'Komersial / Lanud Hasanuddin',
                'classification'   => 'Kelas I Utama',
                'status'           => 'active',
                'is_international' => true,
                'is_active'        => true,
                'data_incomplete'  => false,
                'data_source'      => $srcInjourney,
                'source'           => $srcInjourney,
                'source_url'       => $injourneyUrl,
                'source_checked_at'=> $now,
            ],
            [
                'iata_code'        => 'MDC',
                'icao_code'        => 'WAMM',
                'name'             => 'Sam Ratulangi',
                'city'             => 'Manado',
                'province'         => 'Sulawesi Utara',
                'region'           => 'Region 5',
                'country'          => 'Indonesia',
                'airport_type'     => 'international',
                'management_type'  => $mgmtInjourney,
                'management_name'  => 'PT. Angkasa Pura Indonesia',
                'usage_type'       => 'Komersial / Lanud Sam Ratulangi',
                'classification'   => 'Kelas I Utama',
                'status'           => 'active',
                'is_international' => true,
                'is_active'        => true,
                'data_incomplete'  => false,
                'data_source'      => $srcInjourney,
                'source'           => $srcInjourney,
                'source_url'       => $injourneyUrl,
                'source_checked_at'=> $now,
            ],
            [
                'iata_code'        => 'AMQ',
                'icao_code'        => 'WAPP',
                'name'             => 'Pattimura',
                'city'             => 'Ambon',
                'province'         => 'Maluku',
                'region'           => 'Region 5',
                'country'          => 'Indonesia',
                'airport_type'     => 'international',
                'management_type'  => $mgmtInjourney,
                'management_name'  => 'PT. Angkasa Pura Indonesia',
                'usage_type'       => 'Komersial / Militer',
                'classification'   => 'Kelas I',
                'status'           => 'active',
                'is_international' => true,
                'is_active'        => true,
                'data_incomplete'  => false,
                'data_source'      => $srcInjourney,
                'source'           => $srcInjourney,
                'source_url'       => $injourneyUrl,
                'source_checked_at'=> $now,
            ],
            [
                'iata_code'        => 'DJJ',
                'icao_code'        => 'WAJJ',
                'name'             => 'Sentani',
                'city'             => 'Jayapura',
                'province'         => 'Papua',
                'region'           => 'Region 5',
                'country'          => 'Indonesia',
                'airport_type'     => 'international',
                'management_type'  => $mgmtInjourney,
                'management_name'  => 'PT. Angkasa Pura Indonesia',
                'usage_type'       => 'Komersial',
                'classification'   => 'Kelas I Utama',
                'status'           => 'active',
                'is_international' => true,
                'is_active'        => true,
                'data_incomplete'  => false,
                'data_source'      => $srcInjourney,
                'source'           => $srcInjourney,
                'source_url'       => $injourneyUrl,
                'source_checked_at'=> $now,
            ],
            [
                'iata_code'        => 'BIK',
                'icao_code'        => 'WABB',
                'name'             => 'Frans Kaisiepo',
                'city'             => 'Biak Numfor',
                'province'         => 'Papua',
                'region'           => 'Region 5',
                'country'          => 'Indonesia',
                'airport_type'     => 'international',
                'management_type'  => $mgmtInjourney,
                'management_name'  => 'PT. Angkasa Pura Indonesia',
                'usage_type'       => 'Komersial / Militer',
                'classification'   => 'Kelas I',
                'status'           => 'active',
                'is_international' => true,
                'is_active'        => true,
                'data_incomplete'  => false,
                'data_source'      => $srcInjourney,
                'source'           => $srcInjourney,
                'source_url'       => $injourneyUrl,
                'source_checked_at'=> $now,
            ],

            // ── REGION 6 (4 Bandara: 3 INTL, 1 DOM) ───────────────────────────
            [
                'iata_code'        => 'PNK',
                'icao_code'        => 'WIOO',
                'name'             => 'Supadio',
                'city'             => 'Pontianak / Kubu Raya',
                'province'         => 'Kalimantan Barat',
                'region'           => 'Region 6',
                'country'          => 'Indonesia',
                'airport_type'     => 'international',
                'management_type'  => $mgmtInjourney,
                'management_name'  => 'PT. Angkasa Pura Indonesia',
                'usage_type'       => 'Komersial / Lanud TNI AU',
                'classification'   => 'Kelas I',
                'status'           => 'active',
                'is_international' => true,
                'is_active'        => true,
                'data_incomplete'  => false,
                'data_source'      => $srcInjourney,
                'source'           => $srcInjourney,
                'source_url'       => $injourneyUrl,
                'source_checked_at'=> $now,
            ],
            [
                'iata_code'        => 'BDJ',
                'icao_code'        => 'WAOO',
                'name'             => 'Syamsudin Noor',
                'city'             => 'Banjarmasin / Banjarbaru',
                'province'         => 'Kalimantan Selatan',
                'region'           => 'Region 6',
                'country'          => 'Indonesia',
                'airport_type'     => 'international',
                'management_type'  => $mgmtInjourney,
                'management_name'  => 'PT. Angkasa Pura Indonesia',
                'usage_type'       => 'Komersial / Militer',
                'classification'   => 'Kelas I',
                'status'           => 'active',
                'is_international' => true,
                'is_active'        => true,
                'data_incomplete'  => false,
                'data_source'      => $srcInjourney,
                'source'           => $srcInjourney,
                'source_url'       => $injourneyUrl,
                'source_checked_at'=> $now,
            ],
            [
                'iata_code'        => 'BPN',
                'icao_code'        => 'WALL',
                'name'             => 'Sultan Aji Muhammad Sulaiman Sepinggan',
                'city'             => 'Balikpapan',
                'province'         => 'Kalimantan Timur',
                'region'           => 'Region 6',
                'country'          => 'Indonesia',
                'airport_type'     => 'international',
                'management_type'  => $mgmtInjourney,
                'management_name'  => 'PT. Angkasa Pura Indonesia',
                'usage_type'       => 'Komersial',
                'classification'   => 'Kelas I Utama',
                'status'           => 'active',
                'is_international' => true,
                'is_active'        => true,
                'data_incomplete'  => false,
                'data_source'      => $srcInjourney,
                'source'           => $srcInjourney,
                'source_url'       => $injourneyUrl,
                'source_checked_at'=> $now,
            ],
            [
                'iata_code'        => 'PKY',
                'icao_code'        => 'WAOP',
                'name'             => 'Tjilik Riwut',
                'city'             => 'Palangkaraya',
                'province'         => 'Kalimantan Tengah',
                'region'           => 'Region 6',
                'country'          => 'Indonesia',
                'airport_type'     => 'domestic',
                'management_type'  => $mgmtInjourney,
                'management_name'  => 'PT. Angkasa Pura Indonesia',
                'usage_type'       => 'Komersial',
                'classification'   => 'Kelas II',
                'status'           => 'active',
                'is_international' => false,
                'is_active'        => true,
                'data_incomplete'  => false,
                'data_source'      => $srcInjourney,
                'source'           => $srcInjourney,
                'source_url'       => $injourneyUrl,
                'source_checked_at'=> $now,
            ],

            // ═════════════════════════════════════════════════════════════════
            // PRIORITY 3: REGIONAL / INTERNATIONAL REFERENCE TRANSIT HUBS
            // ═════════════════════════════════════════════════════════════════
            [
                'iata_code'        => 'SIN',
                'icao_code'        => 'WSSS',
                'name'             => 'Changi International Airport',
                'city'             => 'Singapore',
                'province'         => 'Changi',
                'region'           => null,
                'country'          => 'Singapore',
                'airport_type'     => 'international',
                'management_type'  => $mgmtOther,
                'management_name'  => 'Changi Airport Group',
                'usage_type'       => 'Komersial Internasional',
                'classification'   => 'International Hub',
                'status'           => 'active',
                'is_international' => true,
                'is_active'        => true,
                'data_incomplete'  => false,
                'data_source'      => $srcRef,
                'source'           => $srcRef,
                'source_url'       => 'https://www.changiairport.com/',
                'source_checked_at'=> $now,
            ],
            [
                'iata_code'        => 'KUL',
                'icao_code'        => 'WMKK',
                'name'             => 'Kuala Lumpur International Airport',
                'city'             => 'Sepang / Kuala Lumpur',
                'province'         => 'Selangor',
                'region'           => null,
                'country'          => 'Malaysia',
                'airport_type'     => 'international',
                'management_type'  => $mgmtOther,
                'management_name'  => 'Malaysia Airports Holdings Berhad (MAHB)',
                'usage_type'       => 'Komersial Internasional',
                'classification'   => 'International Hub',
                'status'           => 'active',
                'is_international' => true,
                'is_active'        => true,
                'data_incomplete'  => false,
                'data_source'      => $srcRef,
                'source'           => $srcRef,
                'source_url'       => 'https://www.malaysiaairports.com.my/',
                'source_checked_at'=> $now,
            ],
            [
                'iata_code'        => 'JHB',
                'icao_code'        => 'WMKJ',
                'name'             => 'Senai International Airport',
                'city'             => 'Johor Bahru / Senai',
                'province'         => 'Johor',
                'region'           => null,
                'country'          => 'Malaysia',
                'airport_type'     => 'international',
                'management_type'  => $mgmtOther,
                'management_name'  => 'Senai Airport Terminal Services',
                'usage_type'       => 'Komersial Internasional',
                'classification'   => 'International Secondary',
                'status'           => 'active',
                'is_international' => true,
                'is_active'        => true,
                'data_incomplete'  => false,
                'data_source'      => $srcRef,
                'source'           => $srcRef,
                'source_url'       => 'https://www.senaiairport.com/',
                'source_checked_at'=> $now,
            ],
            [
                'iata_code'        => 'DMK',
                'icao_code'        => 'VTBD',
                'name'             => 'Don Mueang International Airport',
                'city'             => 'Bangkok',
                'province'         => 'Bangkok',
                'region'           => null,
                'country'          => 'Thailand',
                'airport_type'     => 'international',
                'management_type'  => $mgmtOther,
                'management_name'  => 'Airports of Thailand (AOT)',
                'usage_type'       => 'Komersial Internasional',
                'classification'   => 'International Secondary',
                'status'           => 'active',
                'is_international' => true,
                'is_active'        => true,
                'data_incomplete'  => false,
                'data_source'      => $srcRef,
                'source'           => $srcRef,
                'source_url'       => 'https://donmueang.airportthai.co.th/',
                'source_checked_at'=> $now,
            ],
            [
                'iata_code'        => 'BKK',
                'icao_code'        => 'VTBS',
                'name'             => 'Suvarnabhumi Airport',
                'city'             => 'Bangkok / Samut Prakan',
                'province'         => 'Samut Prakan',
                'region'           => null,
                'country'          => 'Thailand',
                'airport_type'     => 'international',
                'management_type'  => $mgmtOther,
                'management_name'  => 'Airports of Thailand (AOT)',
                'usage_type'       => 'Komersial Internasional',
                'classification'   => 'International Hub',
                'status'           => 'active',
                'is_international' => true,
                'is_active'        => true,
                'data_incomplete'  => false,
                'data_source'      => $srcRef,
                'source'           => $srcRef,
                'source_url'       => 'https://suvarnabhumi.airportthai.co.th/',
                'source_checked_at'=> $now,
            ],
        ];

        foreach ($airports as $ap) {
            Airport::updateOrCreate(
                ['iata_code' => $ap['iata_code']],
                $ap
            );
        }

        // Enforce Region = null for all non-InJourney airports
        Airport::where('management_type', '!=', Airport::MANAGEMENT_INJOURNEY)->update(['region' => null]);
    }
}
