{{-- reports/partials/footer.blade.php --}}
{{-- Receives: $upload (Upload) --}}
<div class="report-footer">
    <div class="footer-left">Generated by SlotWaves &mdash; {{ \Carbon\Carbon::now()->format('d F Y H:i') }}</div>
    <div class="footer-right">Page <span class="page-number"></span> of <span class="page-count"></span></div>
</div>
